spring.application.name=energia

spring.datasource.url=jdbc:postgresql://localhost:5432/energia_db
spring.datasource.username=postgres
spring.datasource.password=051175Rob
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# === JWT ===
jwt.secret=abcdabcdabcdabcdabcdabcdabcdabcd

jwt.duration=2700000