spring.application.name=energia
server.port=8080

# Configurazione MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/energia_db

# === JWT ===
jwt.secret=abcdabcdabcdabcdabcdabcdabcdabcd
jwt.duration=2700000